apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qtgvi9uht-python
  janus-idp.io/tekton: qtgvi9uht-python
  backstage.io/kubernetes-id: qtgvi9uht-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qtgvi9uht-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
